### ISSUE TITLE
https://fahrraddiebstahl-berlin.de/ seems to be broken

### ISSUE THREAD

**Issue by skomski** [janlemcke/fahrraddiebstahl_berlin#2]
https://fahrraddiebstahl-berlin.de/api/geojson returns only 0 bytes for all my requests.

**Comment by janlemcke** [comment]
It's now working again. Just had to change the file path. Thank's for the hint.

**Comment by pingberlin** [comment]
Hello Jan,

Sadly, it's broken again. Above url return a 404 and the main site a 403 HTTP status.

**Comment by janlemcke** [comment]
Hello,

yeah, i need to migrate the site from one provider to another. May take some time :/ 

Just out of curiosity, what do you use the site for? :)

**Comment by Stoppschildgruen** [comment]
Sadly it still does not work.
